## 📅 Day 2: Autograd Basics

In [1]:
import torch
import numpy as np

In [2]:
x = torch.randn(3, requires_grad=True)
y = x**2 + 3*x
z = y.sum()
z.backward()
print("Gradient of x:", x.grad)

Gradient of x: tensor([3.2021, 0.4206, 4.0457])


In [16]:
# - Create a 2D tensor with requires_grad
x1 = torch.randn((3,4), requires_grad=True)

In [17]:
# - Perform nonlinear transformations (sin, exp, log)
y1 = torch.exp(x1)
z1 = y1.sum()

In [18]:
# - Backprop and inspect gradients
z1.backward(retain_graph=True)
x1.grad

tensor([[0.0554, 1.2574, 3.3953, 1.4568],
        [0.9039, 1.8703, 0.9317, 0.4910],
        [1.7335, 2.3927, 0.5104, 1.2255]])

In [19]:
z1.requires_grad, y1.requires_grad

(True, True)

In [ ]:
z1.backward(retain_graph=True)
x1.grad

tensor([[0.1108, 2.5147, 6.7906, 2.9136],
        [1.8078, 3.7406, 1.8634, 0.9819],
        [3.4671, 4.7855, 1.0209, 2.4510]])

In [ ]:
# - Zero out gradients and recompute to understand accumulation
x1.grad.zero_()

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
z1.backward(retain_graph=True)
x1.grad

tensor([[0.0554, 1.2574, 3.3953, 1.4568],
        [0.9039, 1.8703, 0.9317, 0.4910],
        [1.7335, 2.3927, 0.5104, 1.2255]])

In [27]:
# - Visualize gradient flow by printing .grad after multiple steps
x1 = torch.randn((3,4), requires_grad=True)

def forward(x1):
    return torch.log(torch.nn.functional.softplus(x1) + 1e-6).sum()

for i in range(3):
    z = forward(x1)
    z.backward()
    print(f"step {i} | loss={z.item():.4f} | grad_norm={x1.grad.norm():.4f}")

step 0 | loss=-4.1938 | grad_norm=2.4433
step 1 | loss=-4.1938 | grad_norm=4.8867
step 2 | loss=-4.1938 | grad_norm=7.3300


In [ ]:
# resetting x.grad
for i in range(3):
    x1.grad = None # equivalent to optimizer.zero_grad(set_to_none=True)
    z = forward(x1)
    z.backward()
    print(f"step {i} | loss={z.item():.4f} | grad_norm={x1.grad.norm():.4f}")

step 0 | loss=-4.1938 | grad_norm=2.4433
step 1 | loss=-4.1938 | grad_norm=2.4433
step 2 | loss=-4.1938 | grad_norm=2.4433
