## 📅 Day 1: Tensors and Basic Ops

In [1]:
import torch
import numpy as np

In [3]:
# 1. Create tensors of different data types (float, int, bool)
size = (2,3,)
tensor1 = torch.rand(size, dtype=float)
tensor1

tensor([[9.1631e-01, 9.3539e-01, 3.9632e-04],
        [1.7303e-01, 8.2849e-01, 5.2744e-01]], dtype=torch.float64)

In [6]:
tensor2 = torch.randint(10, size, dtype=int)
tensor2

tensor([[4, 5, 4],
        [9, 4, 8]])

In [9]:
tensor3 = torch.randint(2, size, dtype=bool)
tensor3

tensor([[False, False, False],
        [ True,  True,  True]])

In [10]:
# 2. Convert NumPy array to tensor and back
data = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_numpy = torch.from_numpy(data)
tensor_from_numpy

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
numpy_from_tensor = tensor_from_numpy.numpy()
numpy_from_tensor

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# 3. Try reshaping, slicing, element-wise ops
torch.reshape(tensor1, (-1,))

tensor([9.1631e-01, 9.3539e-01, 3.9632e-04, 1.7303e-01, 8.2849e-01, 5.2744e-01],
       dtype=torch.float64)

In [13]:
tensor11=torch.rand((3,4,), dtype=float)
torch.reshape(tensor11, (2,6,))

tensor([[0.5012, 0.9071, 0.9946, 0.8919, 0.2697, 0.5361],
        [0.6428, 0.7781, 0.4105, 0.0443, 0.0461, 0.5183]], dtype=torch.float64)

In [14]:
tensor11[:,0]

tensor([0.5012, 0.2697, 0.4105], dtype=torch.float64)

In [22]:
tensor12=torch.randint(8, (3,4,))
tensor12

tensor([[1, 1, 3, 1],
        [2, 0, 1, 2],
        [0, 4, 1, 2]])

In [30]:
tensor12.float().dtype, tensor11.dtype

(torch.float32, torch.float64)

In [29]:
tensor12_float = tensor12.to(torch.float64)
tensor11.matmul(tensor12_float.T)

tensor([[5.2838, 3.7806, 6.4067],
        [3.5123, 2.7385, 4.3435],
        [1.1115, 1.9039, 1.2602]], dtype=torch.float64)

In [31]:
tensor11 * tensor12_float

tensor([[0.5012, 0.9071, 2.9837, 0.8919],
        [0.5394, 0.0000, 0.6428, 1.5563],
        [0.0000, 0.1774, 0.0461, 1.0367]], dtype=torch.float64)

In [32]:
torch.accelerator.current_accelerator()

device(type='mps')

In [34]:
# 4. Practice broadcasting rules
torch.cat((tensor11, tensor12))

tensor([[0.5012, 0.9071, 0.9946, 0.8919],
        [0.2697, 0.5361, 0.6428, 0.7781],
        [0.4105, 0.0443, 0.0461, 0.5183],
        [1.0000, 1.0000, 3.0000, 1.0000],
        [2.0000, 0.0000, 1.0000, 2.0000],
        [0.0000, 4.0000, 1.0000, 2.0000]], dtype=torch.float64)

In [35]:
torch.stack((tensor11, tensor12))

tensor([[[0.5012, 0.9071, 0.9946, 0.8919],
         [0.2697, 0.5361, 0.6428, 0.7781],
         [0.4105, 0.0443, 0.0461, 0.5183]],

        [[1.0000, 1.0000, 3.0000, 1.0000],
         [2.0000, 0.0000, 1.0000, 2.0000],
         [0.0000, 4.0000, 1.0000, 2.0000]]], dtype=torch.float64)

In [36]:
torch.stack((tensor11, tensor12), dim=1)

tensor([[[0.5012, 0.9071, 0.9946, 0.8919],
         [1.0000, 1.0000, 3.0000, 1.0000]],

        [[0.2697, 0.5361, 0.6428, 0.7781],
         [2.0000, 0.0000, 1.0000, 2.0000]],

        [[0.4105, 0.0443, 0.0461, 0.5183],
         [0.0000, 4.0000, 1.0000, 2.0000]]], dtype=torch.float64)

In [37]:
# Broadcasted addition
tensor_stack = torch.stack((tensor11, tensor12))
tensor12 + tensor_stack

tensor([[[1.5012, 1.9071, 3.9946, 1.8919],
         [2.2697, 0.5361, 1.6428, 2.7781],
         [0.4105, 4.0443, 1.0461, 2.5183]],

        [[2.0000, 2.0000, 6.0000, 2.0000],
         [4.0000, 0.0000, 2.0000, 4.0000],
         [0.0000, 8.0000, 2.0000, 4.0000]]], dtype=torch.float64)

In [39]:
a = torch.tensor([1, 2, 3])       # shape (3,)
b = torch.tensor([[10], [20]])    # shape (2,1)
a+b

tensor([[11, 12, 13],
        [21, 22, 23]])

In [41]:
# adding a (4,1) tensor to a (1,5) tensor
a = torch.randint(5, (4,1))
b = torch.randint(5, (1,5))
a, b, a+b

(tensor([[0],
         [4],
         [4],
         [1]]),
 tensor([[3, 2, 4, 2, 0]]),
 tensor([[3, 2, 4, 2, 0],
         [7, 6, 8, 6, 4],
         [7, 6, 8, 6, 4],
         [4, 3, 5, 3, 1]]))

In [42]:
# Multiply a (2,3) matrix by a scalar ( )
a = torch.rand((2,3))
a, a*5

(tensor([[0.9749, 0.7367, 0.1567],
         [0.1597, 0.1053, 0.3956]]),
 tensor([[4.8747, 3.6834, 0.7833],
         [0.7986, 0.5264, 1.9780]]))

In [45]:
# Add a (2,3) matrix and a (3,) vector
b = torch.tensor([[1],[0], [-1]])
a+b

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

In [47]:
# 5. Compare tensor operations vs NumPy operations
a @ a.T

tensor([[1.5178, 0.2953],
        [0.2953, 0.1931]])

In [48]:
a_numpy = a.numpy()
a_numpy @ a_numpy.T

array([[1.5177606 , 0.2952602 ],
       [0.2952602 , 0.19309768]], dtype=float32)

In [49]:
a.sum(), a.sum().item()

(tensor(2.5289), 2.528902053833008)

In [ ]:
# check if cuda available
torch.cuda.is_available()

False

In [52]:
# Move tensor to accelerator
if torch.accelerator.is_available():
    a = a.to(torch.accelerator.current_accelerator())

In [53]:
a.shape, a.device

(torch.Size([2, 3]), device(type='mps', index=0))

In [54]:
# - Normalize a 2D tensor (mean 0, std 1)
a = torch.rand((3,4,), dtype=float)
a

tensor([[0.5107, 0.9003, 0.5887, 0.0647],
        [0.1808, 0.3924, 0.2039, 0.0359],
        [0.9799, 0.3536, 0.5866, 0.8187]], dtype=torch.float64)

In [55]:
a.mean(), a.var()

(tensor(0.4680, dtype=torch.float64), tensor(0.1021, dtype=torch.float64))

In [56]:
(a- a.mean())/np.sqrt(a.var())

/var/folders/hg/7ml395w169dbrcxqhmh9wfmw0000gn/T/ipykernel_16500/89870519.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  (a- a.mean())/np.sqrt(a.var())


tensor([[ 0.1335,  1.3532,  0.3778, -1.2623],
        [-0.8989, -0.2366, -0.8268, -1.3525],
        [ 1.6022, -0.3583,  0.3712,  1.0976]], dtype=torch.float64)

In [59]:
# - Compute row-wise and column-wise sums
a.sum(dim=1), a.sum(dim=0), a.sum(dim=-1)

(tensor([2.0645, 0.8130, 2.7388], dtype=torch.float64),
 tensor([1.6714, 1.6463, 1.3792, 0.9193], dtype=torch.float64),
 tensor([2.0645, 0.8130, 2.7388], dtype=torch.float64))

In [61]:
# - Add Gaussian noise to a tensor
b = torch.randn((3,4,))
a + b

tensor([[ 1.7568, -0.1868, -0.7319,  0.9211],
        [ 0.1417,  1.0042,  0.3004, -0.6295],
        [-0.0215,  1.1538, -0.2253,  2.0352]], dtype=torch.float64)

In [74]:
bt = b.T
bt = bt.type_as(a)

a[0,:]@bt[:,0]

tensor(-1.0644, dtype=torch.float64)

In [79]:
# - Implement a dot product manually and compare with torch.matmul
dot_product = torch.zeros((3,3,))

for i in torch.arange(3):
    for j in torch.arange(3):
        dot_product[i,j] = a[i,:] @ bt[:,j]

dot_product

tensor([[-1.0644,  0.5446, -0.1901],
        [-0.4397,  0.2288,  0.0112],
        [ 0.7632, -0.3102, -0.1787]])

In [81]:
matmul = a.matmul(bt)
matmul

tensor([[-1.0644,  0.5446, -0.1901],
        [-0.4397,  0.2288,  0.0112],
        [ 0.7632, -0.3102, -0.1787]], dtype=torch.float64)

In [82]:
# compare two tensors
dot_product = dot_product.type_as(matmul)
dot_product

tensor([[-1.0644,  0.5446, -0.1901],
        [-0.4397,  0.2288,  0.0112],
        [ 0.7632, -0.3102, -0.1787]], dtype=torch.float64)

In [84]:
torch.equal(dot_product, matmul)

False

In [88]:
torch.allclose(dot_product, matmul, atol=1e-8)

True

In [89]:
# - Generate a random 3x3 matrix and compute determinant & inverse
mat = torch.rand((3,3,), dtype=float)
mat

tensor([[0.6839, 0.3392, 0.7149],
        [0.3401, 0.7629, 0.0354],
        [0.1993, 0.8161, 0.9728]], dtype=torch.float64)

In [90]:
mat.inverse()

tensor([[ 1.5249,  0.5419, -1.1404],
        [-0.6922,  1.1178,  0.4681],
        [ 0.2684, -1.0488,  0.8689]], dtype=torch.float64)

In [91]:
mat.det()

tensor(0.4677, dtype=torch.float64)